services:
  db:
    container_name: "db"
    image: postgres:11.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prisma

  # The API is better launched using `npm run dev` for hot reloading
  api:
    container_name: graphql-api
    build: .
    env_file:
      - ./.env.docker
    command: >
      sh -c '
      sleep 5 &&
      npx prisma migrate dev --name init &&
      npx prisma generate'
    ports:
      - 4000:4000
    depends_on:
      - db