services:
  db:
    container_name: "db"
    image: postgres:11.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prisma

  # The API is better launched using `npm run dev` for hot reloading
  # api:
  #   container_name: graphql-api
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile
  #   env_file:
  #     - ./backend/.env.dev
  #   ports:
  #     - 4000:4000

