version: '3'

services:
  db:
    container_name: postgres-docker
    image: postgres:11.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      COMPOSE_PROJECT_NAME: minidesk_api_compose

  pgAdmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "80:80"
    depends_on:
      - db

  api:
    container_name: -graphql-api
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env.dev
    ports:
      - 4000:4000
    # depends_on:
