version: '3'

services:
  db:
    container_name: postgres-docker
    image: postgres:11.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      COMPOSE_PROJECT_NAME: minidesk_api_compose

  prisma:
    image: prismagraphql/prisma:1.21
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            active: true
            host: db
            port: 5432
            user: postgres
            password: password
            # migrations: true
    depends_on:
      - api
      - db

  # The API is better launched using `npm run dev` for hot reloading
  # api:
  #   container_name: graphql-api
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile
  #   env_file:
  #     - ./backend/.env.dev
  #   ports:
  #     - 4000:4000
